services:

#---------------------------------BACKEND--------------------------------
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - recollect
    volumes:
      - ./backend/uploads:/app/uploads
      - ./test_images:/app/test_images
    # restart: always

#--------------------------------DATABASE--------------------------------

  postgres:
    image: postgres:18
    container_name: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "pg_stat_statements.max=10000"
    networks:
      - recollect
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d
    # restart: always

#----------------------------------REDIS---------------------------------

  redis:
    image: redis:8-bookworm
    container_name: redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --maxmemory 200mb
      --maxmemory-policy allkeys-lru
    networks:
      - recollect
    volumes:
      - redis_data:/data
    # restart: always

#--------------------------------VOLUMES---------------------------------

volumes:
  postgres_data:
    name: postgres_data
    driver: local
  redis_data:
    name: redis_data
    driver: local

#--------------------------------NETWORKS--------------------------------

networks:
  recollect:
    name: recollect
    ipam:
      config:
        - subnet: 172.18.0.0/16